/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdproiect;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class FereastraOperatiuni extends javax.swing.JFrame {

    /**
     * Creates new form FereastraOperatiuni
     */
    public FereastraOperatiuni() {
        initComponents();
        this.getContentPane().setBackground(new Color(0 , 153, 153));
        this.setTitle("OPERATIUNI ");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonAngajati = new javax.swing.JButton();
        butnColete = new javax.swing.JButton();
        butonClienti = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        butonAngajati.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butonAngajati.setText("ANGAJATI");
        butonAngajati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAngajatiActionPerformed(evt);
            }
        });

        butnColete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butnColete.setText("COLETE");
        butnColete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnColeteActionPerformed(evt);
            }
        });

        butonClienti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butonClienti.setText("CLIENTI");
        butonClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonClientiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Raport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(butonAngajati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butnColete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonClienti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(butonAngajati, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(butnColete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(butonClienti, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonAngajatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAngajatiActionPerformed
        FereastraAngajati open=new FereastraAngajati();
    
        open.setVisible(true);
    }//GEN-LAST:event_butonAngajatiActionPerformed

    private void butnColeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnColeteActionPerformed
        // TODO add your handling code here:
        FereastraColete open = new FereastraColete();
       
        open.setVisible(true);
    }//GEN-LAST:event_butnColeteActionPerformed

    private void butonClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonClientiActionPerformed
        // TODO add your handling code here:
        FereastraClienti open = new FereastraClienti();
        
        open.setVisible(true);
    }//GEN-LAST:event_butonClientiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Statement stmt;
         int  total_colete=0,total_angajati = 0,total_clienti = 0;
        try {
            Connection con = Conexiune.DBConector();
            stmt = (Statement) con.createStatement();
            String query = "Select count(coda) from angajati"; 
            String query2 = "Select count(codcli) from clienti"; 
            String query3 = "Select count(codc) from colet"; 
      

            PreparedStatement st = con.prepareStatement(query);
            PreparedStatement st2 = con.prepareStatement(query2);
            PreparedStatement st3 = con.prepareStatement(query3);
       
            ResultSet rs = st.executeQuery();
            ResultSet rs2 = st2.executeQuery();
            ResultSet rs3 = st3.executeQuery();
            while(rs.next()){
                total_angajati=Integer.parseInt(rs.getString(1));
            }
            while(rs2.next()){
                total_clienti=Integer.parseInt(rs2.getString(1));
                
            }
            while(rs3.next()){
                total_colete=Integer.parseInt((rs3.getString(1)));
            }
            FereastraAfisare open = new FereastraAfisare();
            open.setVisible(true);
            open.afisareFereastra.append("Pana la aceasta data avem:"+"\n"+"1.Un numar de "+total_angajati+" angajati"+"\n"+"2.In total avem: "+total_clienti+" clienti"
                    +"\n"+"3. "+total_colete+" colete inregistrate");
            } 
        
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraOperatiuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraOperatiuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraOperatiuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraOperatiuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FereastraOperatiuni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butnColete;
    private javax.swing.JButton butonAngajati;
    private javax.swing.JButton butonClienti;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
