/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdproiect;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class IntroducereColet extends javax.swing.JFrame {

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    /**
     * Creates new form IntroducereColet
     */
    public IntroducereColet() {
        initComponents();
        this.getContentPane().setBackground(new Color(0 , 152, 152));
        this.setTitle("Modificare Client");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        Statement stmt;
        try {
            Connection con = Conexiune.DBConector();
            stmt = (Statement) con.createStatement();
            String query = "Select nume,prenume from clienti";
            String query2 = "Select nume,prenume from angajati";
            PreparedStatement st = con.prepareStatement(query);
            PreparedStatement st2 = con.prepareStatement(query2);
            ResultSet rs = st.executeQuery();
            ResultSet rs2 = st2.executeQuery();
            //textAfisare.append("CODA"+"\t"+"Nume"+"\t"+"Prenume"+"\t"+"CNP"+"\t"+"Adresa"+"\t"+"Salariu"+"\t"+"CodF"+"\n"+"\n");
            while (rs.next()) {
                comboClient.addItem(rs.getString("nume") + " " + rs.getString("prenume"));

            }
            while (rs2.next()) {
                comboAngajat.addItem(rs2.getString("nume") + " " + rs2.getString("prenume"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textCodColet = new javax.swing.JTextField();
        comboClient = new javax.swing.JComboBox<>();
        textDestinatar = new javax.swing.JTextField();
        textAdresa = new javax.swing.JTextField();
        textGreutate = new javax.swing.JTextField();
        textSuma = new javax.swing.JTextField();
        comboAngajat = new javax.swing.JComboBox<>();
        butonOk = new javax.swing.JButton();
        dataPreluare = new org.jdesktop.swingx.JXDatePicker();
        dataPredare = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("Introducere Colet");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Cod Colet");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Client");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Destinatar");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Adresa Destinatar");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Data preluare");

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Data Predare");

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("Greutate");

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("Suma");

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setText("Angajat");

        textCodColet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodColetKeyTyped(evt);
            }
        });

        comboClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientActionPerformed(evt);
            }
        });

        textGreutate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textGreutateKeyTyped(evt);
            }
        });

        textSuma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSumaKeyTyped(evt);
            }
        });

        butonOk.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        butonOk.setText("OK");
        butonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textCodColet)
                            .addComponent(textDestinatar)
                            .addComponent(dataPreluare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(dataPredare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textAdresa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textGreutate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textSuma, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboAngajat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCodColet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textDestinatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataPreluare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dataPredare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textGreutate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboAngajat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(butonOk)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOkActionPerformed
        String destinatar, adresa;
        int codc = 0, suma = 0, greutate = 0;

        Statement stmt = null;
        PreparedStatement ps = null;
        boolean ok = false;
        destinatar = textDestinatar.getText();

        adresa = textAdresa.getText();

        try {
            codc = Integer.parseInt(textCodColet.getText());
            suma = Integer.parseInt(textSuma.getText());
            greutate = Integer.parseInt(textGreutate.getText());

        } catch (NumberFormatException ex) {

        }
        try {
            Connection con = Conexiune.DBConector();
            stmt = (Statement) con.createStatement();
            if (textDestinatar.getText().length() == 0 || textAdresa.getText().length() == 0 || textCodColet.getText().length() == 0 || textSuma.getText().length() == 0
                    || textGreutate.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "TOATE CAMPURILE SUNT OBLIGATORII!", "Error", 1);
                ok = false;
            } else if (textDestinatar.getText() == null || textAdresa.getText() == null || textCodColet.getText() == null || textSuma.getText() == null || textGreutate.getText() == null) {
                ok = false;
            } else {
                ok = true;
            }

            if (ok == true) {
                ps = con.prepareStatement("insert into  colet(codc, codcli, destinatar, adr_dest, preluare, predare, greutate, suma,coda) values (?,?,?,?,?,?,?,?,?)");
                PreparedStatement st = con.prepareStatement("Select codcli from clienti where nume=? and prenume=?");
                int codclient=0;
                String nume = comboClient.getSelectedItem().toString();
                String[] numebun = nume.split(" ");
                st.setString(1, numebun[0].toString());
                st.setString(2, numebun[1].toString());
                st.executeQuery();
                ResultSet rs = st.getResultSet();
               
                while (rs.next()) {
                    codclient=Integer.parseInt(rs.getString(1));
                    
                }
                PreparedStatement st2 = con.prepareStatement("Select coda from angajati where nume=? and prenume=?");
                int coda=0;
                String numea = comboAngajat.getSelectedItem().toString();
                String[] numebun2 = numea.split(" ");
             
                st2.setString(1, numebun2[0].toString());
                st2.setString(2, numebun2[1].toString());
                st2.executeQuery();
              
                ResultSet rs2 = st2.getResultSet();
               
                while (rs2.next()) {
                    coda=Integer.parseInt(rs2.getString(1));
                    
                }
                
                ps.setInt(1, codc);
                ps.setInt(2, codclient);
                ps.setString(3, destinatar);
                ps.setString(4, adresa);

                ps.setDate(5, convertJavaDateToSqlDate(dataPreluare.getDate()));
                ps.setDate(6, convertJavaDateToSqlDate(dataPredare.getDate()));
                ps.setInt(7, greutate);
                ps.setInt(8, suma);
                ps.setInt(9, coda);
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Coletul fost introdus in baza de date!");
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_butonOkActionPerformed

    private void textCodColetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodColetKeyTyped
        IntroducereClient metoda= new IntroducereClient();
        metoda.check(evt);
         if(textCodColet.getText().length()>3){
           evt.consume();
       }
    }//GEN-LAST:event_textCodColetKeyTyped

    private void textGreutateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textGreutateKeyTyped
        // TODO add your handling code here:
        IntroducereClient metoda= new IntroducereClient();
        metoda.check(evt);
         if(textGreutate.getText().length()>3){
           evt.consume();
         }
    }//GEN-LAST:event_textGreutateKeyTyped

    private void textSumaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSumaKeyTyped
      IntroducereClient metoda= new IntroducereClient();
        metoda.check(evt);
         if(textSuma.getText().length()>4){
           evt.consume();
         }
    }//GEN-LAST:event_textSumaKeyTyped

    private void comboClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducereColet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducereColet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducereColet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducereColet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroducereColet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonOk;
    private javax.swing.JComboBox<String> comboAngajat;
    private javax.swing.JComboBox<String> comboClient;
    private org.jdesktop.swingx.JXDatePicker dataPredare;
    private org.jdesktop.swingx.JXDatePicker dataPreluare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textAdresa;
    private javax.swing.JTextField textCodColet;
    private javax.swing.JTextField textDestinatar;
    private javax.swing.JTextField textGreutate;
    private javax.swing.JTextField textSuma;
    // End of variables declaration//GEN-END:variables
}
