/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdproiect;

import bdproiect.Conexiune;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class IntroducereAngajati extends javax.swing.JFrame {

    boolean ok = false;
    public  void check(java.awt.event.KeyEvent evt){
        char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        evt.consume();
                    }
    }
    /**
     * Creates new form IntroducereAngajati
     */
    public IntroducereAngajati() {
        initComponents();

        this.setFont(new Font("Cambria", Font.BOLD, 12));
        this.getContentPane().setBackground(new Color(0 , 152, 152));
        this.setTitle("Introducere angajat nou");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
         Statement stmt;
        try {
            Connection con = Conexiune.DBConector();
            stmt = (Statement) con.createStatement();
            String query = "Select * from functie";

            PreparedStatement st = con.prepareStatement(query);

            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                comboFunctie.addItem(rs.getString("codf") + " " + rs.getString("denumire"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCoda = new javax.swing.JTextField();
        textNume = new javax.swing.JTextField();
        textPrenume = new javax.swing.JTextField();
        textCNP = new javax.swing.JTextField();
        textAdresa = new javax.swing.JTextField();
        butonOK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textSal = new javax.swing.JTextField();
        comboFunctie = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel1.setText("Cod Angajat");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel2.setText("Nume");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel3.setText("Prenume");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel4.setText("CNP");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel5.setText("Adresa");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel6.setText("Cod Functie");

        textCoda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textCodaCaretUpdate(evt);
            }
        });
        textCoda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCodaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodaKeyTyped(evt);
            }
        });

        textCNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCNPActionPerformed(evt);
            }
        });
        textCNP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCNPKeyTyped(evt);
            }
        });

        butonOK.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        butonOK.setText("OK");
        butonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOKActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel7.setText("Detalii Angajat");

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel8.setText("Salariu");

        textSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(35, 35, 35))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(72, 72, 72)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textAdresa)
                    .addComponent(textPrenume)
                    .addComponent(textNume)
                    .addComponent(textCoda)
                    .addComponent(textCNP)
                    .addComponent(textSal, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(comboFunctie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCoda)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboFunctie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(butonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCNPActionPerformed

    private void butonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOKActionPerformed
        String nume, prenume, adresa;
        String nume2 = comboFunctie.getSelectedItem().toString();
        String[] numebun = nume2.split(" ");
        int coda = 0, codf=0, sal=0;
        long  cnp=0;
        Statement stmt = null;
        PreparedStatement ps = null;
        
        nume = textNume.getText();
        prenume = textPrenume.getText();
        
        adresa = textAdresa.getText();
        
        try{
            coda = Integer.parseInt(textCoda.getText());
            cnp = Long.parseLong(textCNP.getText());
            sal = Integer.parseInt(textSal.getText());
            
        }
        catch(NumberFormatException ex){
           
        }
        try {
            Connection con = Conexiune.DBConector();
            stmt = (Statement) con.createStatement();
            if (textCoda.getText().length()==0 || nume.length() == 0 || prenume.length() == 0 || textCNP.getText().isEmpty() || adresa.length() == 0 ||
                    textSal.getText().length()==0 ) {
                JOptionPane.showMessageDialog(null, "TOATE CAMPURILE SUNT OBLIGATORII!", "Error", 1);
                ok = false;
            } 
            else if(textCoda.getText()==null || textNume.getText()==null || textPrenume.getText()==null || textCNP.getText()==null
                    || textAdresa.getText()==null || textSal.getText()==null  ) 
                 ok=false;
             else {
                ok = true;
            }
            
           
            if (ok == true) {
                ps = con.prepareStatement("insert into  angajati(coda,nume,prenume,cnp,adresa,salariu,codf) values (?,?,?,?,?,?,?)");
                ps.setInt(1, coda);
                ps.setString(2, nume);
                ps.setString(3, prenume);
                ps.setLong(4, cnp);
                ps.setString(5, adresa);
                ps.setInt(6, sal);
                ps.setString(7, numebun[0]);
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Angajatul a fost introdus in baza de date!");
                    textCoda.setText("");
                    textNume.setText("");
                    textPrenume.setText("");
                    textCNP.setText("");
                    textAdresa.setText("");
                    textSal.setText("");
                    
                    
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }

    }//GEN-LAST:event_butonOKActionPerformed

    private void textCodaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodaKeyPressed

    private void textCodaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textCodaCaretUpdate
       
  
    }//GEN-LAST:event_textCodaCaretUpdate

    private void textCodaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodaKeyTyped
       check(evt);
       if(textCoda.getText().length()>3){
           evt.consume();
       }
    }//GEN-LAST:event_textCodaKeyTyped

    private void textCNPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCNPKeyTyped
       check(evt);
       if(textCNP.getText().length()>12){
           evt.consume();
       }
    }//GEN-LAST:event_textCNPKeyTyped

    private void textSalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSalKeyTyped
        // TODO add your handling code here:
        check(evt);
       if(textSal.getText().length()>8){
           evt.consume();
       }
    }//GEN-LAST:event_textSalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducereAngajati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducereAngajati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducereAngajati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducereAngajati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroducereAngajati().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonOK;
    private javax.swing.JComboBox<String> comboFunctie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textAdresa;
    private javax.swing.JTextField textCNP;
    private javax.swing.JTextField textCoda;
    private javax.swing.JTextField textNume;
    private javax.swing.JTextField textPrenume;
    private javax.swing.JTextField textSal;
    // End of variables declaration//GEN-END:variables
}
