/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdproiect;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class ListaColete extends javax.swing.JFrame {

    /**
     * Creates new form ListaColete
     */
    public ListaColete() {
        initComponents();
        this.getContentPane().setBackground(new Color(0 , 152, 152));
        this.setTitle("Cautare Angajati");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boxAfisare = new javax.swing.JComboBox<>();
        boxSortare = new javax.swing.JComboBox<>();
        butonOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Afiseaza: ");

        boxAfisare.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        boxAfisare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toate coletele", "Sortate" }));

        boxSortare.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        boxSortare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cod Colet Crescator", "Cod Colet Descrescator", "Cod Client Crescator", "Cod Client Descrescator", "Destinatar A-Z", "Destinatar Z-A", "Greutate Crescator", "Greutate Descrescator", "Suma Crescator", "Suma Descrescator" }));

        butonOk.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        butonOk.setText("Afiseaza");
        butonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOkActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("Optiuni Afisare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butonOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(131, 131, 131)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxAfisare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(boxSortare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxAfisare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(boxSortare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(butonOk)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOkActionPerformed
        String selectie = boxAfisare.getSelectedItem().toString();
        String sortare = boxSortare.getSelectedItem().toString();
        String query=null;
        if(selectie.equals("Toate coletele")){
           query = "Select * from colet";
        }
        
        if(selectie.equals("Sortate")){
            if(sortare.equals("Cod Colet Crescator"))
                query = "Select * from colet ORDER BY codc ASC";
            if(sortare.equals("Cod Colet Descrescator"))
                query = "Select * from colet ORDER BY codc DESC";
            if(sortare.equals("Cod Client Crescator"))
                query = "Select * from colet ORDER BY codcli ASC";
            if(sortare.equals("Cod Client Descrescator"))
                query = "Select * from colet ORDER BY codc DESC";
            if(sortare.equals("Destinatar A-Z"))
                query = "Select * from colet ORDER BY destinatar ASC";
            if(sortare.equals("Destinatar Z-A"))
                query = "Select * from colet ORDER BY destinatar DESC";
            if(sortare.equals("Greutate Crescator"))
                query = "Select * from colet ORDER BY greutate ASC";
            if(sortare.equals("Greutate Descrescator"))
                query = "Select * from colet ORDER BY greutate DESC";
            if(sortare.equals("Suma Crescator"))
                query = "Select * from colet ORDER BY suma ASC";
            if(sortare.equals("Suma Descrescator"))
                query = "Select * from colet ORDER BY suma DESC";
                       }
        Statement stmt;
        try{
        Connection con = Conexiune.DBConector();
            stmt = (Statement) con.createStatement();
            
            PreparedStatement st = con.prepareStatement(query);
            ResultSet rs = st.executeQuery();
            FereastraAfisare metoda= new FereastraAfisare();
            metoda.setVisible(true);
            metoda.afisareFereastra.append("COD COlet"+"\t"+"Cod Client"+"\t"+"Destinatar"+"\t"+"Adr Dest"+"\t"+"Preluare"+"\t"+"\t"+"Predare"+"\t"+"\t"+"Greutate"+"\t"+"Suma"+"\t"+"Cod Angajat"+"\n");
            while(rs.next()){
                
                metoda.afisareFereastra.append(rs.getString("codc")+"\t"+rs.getString("codcli")+"\t"+rs.getString("destinatar")+"\t"+
                        rs.getString("adr_dest")+"\t"+rs.getString("preluare")+"\t"+rs.getString("predare")+"\t"+rs.getString("greutate")+"\t"+rs.getString("suma")+"\t"+
                        rs.getString("coda")+"\t"+"\n");
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
        
        
    }//GEN-LAST:event_butonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaColete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaColete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaColete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaColete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaColete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAfisare;
    private javax.swing.JComboBox<String> boxSortare;
    private javax.swing.JButton butonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
